cd V:\roms\psx
ren *.CD1 *.chd
ren *.CD2 *.chd
ren *.CD3 *.chd
ren *.CD4 *.chd
ren *.CD5 *.chd
powershell -Command "Invoke-Command -scriptblock {$ErrorActionPreference = 'SilentlyContinue';Get-Childitem *.m3u -depth 1 | ForEach {((Get-Content -Path $_ -Raw) -replace '.CD1|.CD2|.CD3|.CD4|.CD5','.chd') | Set-Content -Path $_ }}"
attrib +h "70's Robot Anime - Geppy-X - The Super Boosted Armor (Japan) (Disc 1).chd"
attrib +h "70's Robot Anime - Geppy-X - The Super Boosted Armor (Japan) (Disc 2).chd"
attrib +h "70's Robot Anime - Geppy-X - The Super Boosted Armor (Japan) (Disc 3).chd"
attrib +h "70's Robot Anime - Geppy-X - The Super Boosted Armor (Japan) (Disc 4).chd"
attrib +h "Alone in the Dark - The New Nightmare (USA) (Disc 1).chd"
attrib +h "Alone in the Dark - The New Nightmare (USA) (Disc 2).chd"
attrib +h "Animetic Story Game 1 - Card Captor Sakura (Japan) (Disc 1).chd"
attrib +h "Animetic Story Game 1 - Card Captor Sakura (Japan) (Disc 2).chd"
attrib +h "Armored Core - Master of Arena (USA) (Disc 1).chd"
attrib +h "Armored Core - Master of Arena (USA) (Disc 2).chd"
attrib +h "Baldur's Gate - Disc 1.chd"
attrib +h "Baldur's Gate - Disc 2.chd"
attrib +h "Baldur's Gate - Disc 3.chd"
attrib +h "BrainDead 13 (USA) (Disc 1).chd"
attrib +h "BrainDead 13 (USA) (Disc 2).chd"
attrib +h "Chrono Cross (USA) (Disc 1).chd"
attrib +h "Chrono Cross (USA) (Disc 2).chd"
attrib +h "Colony Wars (USA) (Disc 1).chd"
attrib +h "Colony Wars (USA) (Disc 2).chd"
attrib +h "Countdown Vampires (USA) (Disc 1).chd"
attrib +h "Countdown Vampires (USA) (Disc 2).chd"
attrib +h "Covert Ops - Nuclear Dawn (USA) (Disc 1).chd"
attrib +h "Covert Ops - Nuclear Dawn (USA) (Disc 2).chd"
attrib +h "Cyberwar (Japan) (Disc 1).chd"
attrib +h "Cyberwar (Japan) (Disc 2).chd"
attrib +h "Cyberwar (Japan) (Disc 3).chd"
attrib +h "D (USA) (Disc 1).chd"
attrib +h "D (USA) (Disc 2).chd"
attrib +h "D (USA) (Disc 3).chd"
attrib +h "Dracula - The Last Sanctuary (USA) (Disc 1).chd"
attrib +h "Dracula - The Last Sanctuary (USA) (Disc 2).chd"
attrib +h "Dracula - The Resurrection (USA) (Disc 1).chd"
attrib +h "Dracula - The Resurrection (USA) (Disc 2).chd"
attrib +h "Dragon Valor (USA) (Disc 1).chd"
attrib +h "Dragon Valor (USA) (Disc 2).chd"
attrib +h "Dragon Warrior VII (USA) (Disc 1).chd"
attrib +h "Dragon Warrior VII (USA) (Disc 2).chd"
attrib +h "Driver 2 (USA) (Disc 1).chd"
attrib +h "Driver 2 (USA) (Disc 2).chd"
attrib +h "Evil Dead - Hail to the King (USA) (Disc 1).chd"
attrib +h "Evil Dead - Hail to the King (USA) (Disc 2).chd"
attrib +h "Fear Effect (Europe) (Disc 1).chd"
attrib +h "Fear Effect (Europe) (Disc 2).chd"
attrib +h "Fear Effect (Europe) (Disc 3).chd"
attrib +h "Fear Effect (Europe) (Disc 4).chd"
attrib +h "Fear Effect 2 - Retro Helix (USA) (Disc 1).chd"
attrib +h "Fear Effect 2 - Retro Helix (USA) (Disc 2).chd"
attrib +h "Fear Effect 2 - Retro Helix (USA) (Disc 3).chd"
attrib +h "Fear Effect 2 - Retro Helix (USA) (Disc 4).chd"
attrib +h "Final Fantasy IX (USA) (Disc 1).chd"
attrib +h "Final Fantasy IX (USA) (Disc 2).chd"
attrib +h "Final Fantasy IX (USA) (Disc 3).chd"
attrib +h "Final Fantasy IX (USA) (Disc 4).chd"
attrib +h "Final Fantasy VII (USA) (Disc 1).chd"
attrib +h "Final Fantasy VII (USA) (Disc 2).chd"
attrib +h "Final Fantasy VII (USA) (Disc 3).chd"
attrib +h "Final Fantasy VIII (USA) (Disc 1).chd"
attrib +h "Final Fantasy VIII (USA) (Disc 2).chd"
attrib +h "Final Fantasy VIII (USA) (Disc 3).chd"
attrib +h "Final Fantasy VIII (USA) (Disc 4).chd"
attrib +h "Fox Hunt (USA) (Disc 1).chd"
attrib +h "Fox Hunt (USA) (Disc 2).chd"
attrib +h "Fox Hunt (USA) (Disc 3).chd"
attrib +h "Galerians (USA) (Disc 1).chd"
attrib +h "Galerians (USA) (Disc 2).chd"
attrib +h "Galerians (USA) (Disc 3).chd"
attrib +h "Golden Nugget (USA) (Disc 1).chd"
attrib +h "Golden Nugget (USA) (Disc 2).chd"
attrib +h "G-Police (USA) (Disc 1).chd"
attrib +h "G-Police (USA) (Disc 2).chd"
attrib +h "Gran Turismo 2 (Europe) (Disc 1) (Arcade Mode).chd"
attrib +h "Gran Turismo 2 (Europe) (Disc 2) (Gran Turismo Mode).chd"
attrib +h "Grandia (USA) (Disc 1).chd"
attrib +h "Grandia (USA) (Disc 2).chd"
attrib +h "Heart of Darkness (USA) (Disc 1).chd"
attrib +h "Heart of Darkness (USA) (Disc 2).chd"
attrib +h "Hive, The (USA) (Disc 1).chd"
attrib +h "Hive, The (USA) (Disc 2).chd"
attrib +h "In Cold Blood (USA) (Disc 1).chd"
attrib +h "In Cold Blood (USA) (Disc 2).chd"
attrib +h "Juggernaut (USA) (Disc 1).chd"
attrib +h "Juggernaut (USA) (Disc 2).chd"
attrib +h "Juggernaut (USA) (Disc 3).chd"
attrib +h "Koudelka (USA) (Disc 1).chd"
attrib +h "Koudelka (USA) (Disc 2).chd"
attrib +h "Koudelka (USA) (Disc 3).chd"
attrib +h "Koudelka (USA) (Disc 4).chd"
attrib +h "Legend of Dragoon, The (USA) (Disc 1).chd"
attrib +h "Legend of Dragoon, The (USA) (Disc 2).chd"
attrib +h "Legend of Dragoon, The (USA) (Disc 3).chd"
attrib +h "Legend of Dragoon, The (USA) (Disc 4).chd"
attrib +h "Lunar - Silver Star Story Complete (USA) (Disc 1).chd"
attrib +h "Lunar - Silver Star Story Complete (USA) (Disc 2).chd"
attrib +h "Lunar 2 - Eternal Blue Complete (USA) (Disc 1).chd"
attrib +h "Lunar 2 - Eternal Blue Complete (USA) (Disc 2).chd"
attrib +h "Lunar 2 - Eternal Blue Complete (USA) (Disc 3).chd"
attrib +h "Metal Gear Solid (USA) (Disc 1).chd"
attrib +h "Metal Gear Solid (USA) (Disc 2).chd"
attrib +h "Novastorm (USA) (Disc 1).chd"
attrib +h "Novastorm (USA) (Disc 2).chd"
attrib +h "Oddworld - Abe's Exoddus (USA) (Disc 1).chd"
attrib +h "Oddworld - Abe's Exoddus (USA) (Disc 2).chd"
attrib +h "Parasite Eve (USA) (Disc 1).chd"
attrib +h "Parasite Eve (USA) (Disc 2).chd"
attrib +h "Parasite Eve II (USA) (Disc 1).chd"
attrib +h "Parasite Eve II (USA) (Disc 2).chd"
attrib +h "Policenauts (Japan) (Disc 1) [En by Slowbeef v1.0].chd"
attrib +h "Policenauts (Japan) (Disc 2) [En by Slowbeef v1.0].chd"
attrib +h "Psychic Detective (USA) (Disc 1).chd"
attrib +h "Psychic Detective (USA) (Disc 2).chd"
attrib +h "Psychic Detective (USA) (Disc 3).chd"
attrib +h "Resident Evil 2 (Europe) (Disc 1).chd"
attrib +h "Resident Evil 2 (Europe) (Disc 2).chd"
attrib +h "Riven - The Sequel to Myst (USA) (Disc 1).chd"
attrib +h "Riven - The Sequel to Myst (USA) (Disc 2).chd"
attrib +h "Riven - The Sequel to Myst (USA) (Disc 3).chd"
attrib +h "Riven - The Sequel to Myst (USA) (Disc 4).chd"
attrib +h "Riven - The Sequel to Myst (USA) (Disc 5).chd"
attrib +h "Shadow Madness (USA) (Disc 1).chd"
attrib +h "Shadow Madness (USA) (Disc 2).chd"
attrib +h "Shockwave Assault (USA) (Disc 1) (Shockwave - Invasion Earth).chd"
attrib +h "Shockwave Assault (USA) (Disc 2) (Shockwave - Operation Jumpgate).chd"
attrib +h "Star Ocean - The Second Story (USA) (Disc 1).chd"
attrib +h "Star Ocean - The Second Story (USA) (Disc 2).chd"
attrib +h "Star Wars - Rebel Assault II - The Hidden Empire (USA) (Disc 1).chd"
attrib +h "Star Wars - Rebel Assault II - The Hidden Empire (USA) (Disc 2).chd"
attrib +h "Syphon Filter 2 (USA) (Disc 1).chd"
attrib +h "Syphon Filter 2 (USA) (Disc 2).chd"
attrib +h "Tales of Destiny II (USA) (Disc 1).chd"
attrib +h "Tales of Destiny II (USA) (Disc 2).chd"
attrib +h "Tales of Destiny II (USA) (Disc 3).chd"
attrib +h "Thousand Arms (USA) (Disc 1).chd"
attrib +h "Thousand Arms (USA) (Disc 2).chd"
attrib +h "Valkyrie Profile (USA) (Disc 1).chd"
attrib +h "Valkyrie Profile (USA) (Disc 2).chd"
attrib +h "Wild Arms 2 (USA) (Disc 1).chd"
attrib +h "Wild Arms 2 (USA) (Disc 2).chd"
attrib +h "Wing Commander III - Heart of the Tiger (USA) (Disc 1).chd"
attrib +h "Wing Commander III - Heart of the Tiger (USA) (Disc 2).chd"
attrib +h "Wing Commander III - Heart of the Tiger (USA) (Disc 3).chd"
attrib +h "Wing Commander III - Heart of the Tiger (USA) (Disc 4).chd"
attrib +h "Wing Commander IV - The Price of Freedom (USA) (Disc 1).chd"
attrib +h "Wing Commander IV - The Price of Freedom (USA) (Disc 2).chd"
attrib +h "Wing Commander IV - The Price of Freedom (USA) (Disc 3).chd"
attrib +h "Wing Commander IV - The Price of Freedom (USA) (Disc 4).chd"
attrib +h "Xenogears (USA) (Disc 1).chd"
attrib +h "Xenogears (USA) (Disc 2).chd"
attrib +h "X-Files, The (USA) (Disc 1).chd"
attrib +h "X-Files, The (USA) (Disc 2).chd"
attrib +h "X-Files, The (USA) (Disc 3).chd"
attrib +h "X-Files, The (USA) (Disc 4).chd"