ren "Track 10.flac" "Track10.flac"
ren "Track 11.flac" "Track11.flac"
ren "Track 12.flac" "Track12.flac"
ren "Track 13.flac" "Track13.flac"
ren "Track 14.flac" "Track14.flac"
ren "Track 15.flac" "Track15.flac"
ren "Track 16.flac" "Track16.flac"
ren "Track 17.flac" "Track17.flac"
ren "Track 18.flac" "Track18.flac"
ren "Track 19.flac" "Track19.flac"
ren "Track 20.flac" "Track20.flac"
ren "Track 21.flac" "Track21.flac"
ren "Track 22.flac" "Track22.flac"
ren "Track 23.flac" "Track23.flac"
ren "Track 24.flac" "Track24.flac"
ren "Track 25.flac" "Track25.flac"
ren "Track 26.flac" "Track26.flac"
ren "Track 27.flac" "Track27.flac"
ren "Track 28.flac" "Track28.flac"
ren "Track 29.flac" "Track29.flac"
ren "Track  2.flac" "Track 2.flac"
ren "Track 30.flac" "Track30.flac"
ren "Track  3.flac" "Track 3.flac"
ren "Track  4.flac" "Track 4.flac"
ren "Track  5.flac" "Track 5.flac"
ren "Track  6.flac" "Track 6.flac"
ren "Track  7.flac" "Track 7.flac"
ren "Track  8.flac" "Track 8.flac"
ren "Track  9.flac" "Track 9.flac"
