copy gamelist.xml V:\roms\scummvm
cd V:\roms\scummvm
del /s *.scummvm
del ".\gob3cd.svm\gob3cd.scummvm"
del ".\hoyle1.svm\hoyle1.scummvm"
del ".\nippon.svm\nippon.scummvm"
del ".\kyra3.svm\kyra3.scummvm"
del ".\teenagent.svm\teenagent.scummvm"
del ".\comi.svm\comi.scummvm"
del ".\woodruff-gb.svm\woodruff-gb.scummvm"
del ".\fairytales.svm\fairytales.scummvm"
del ".\pepper.svm\pepper.scummvm"
del ".\bargon.svm\bargon.scummvm"
del ".\manhole-cd.svm\manhole-cd.scummvm"
del ".\draci.svm\draci.scummvm"
del ".\troll.svm\troll.scummvm"
del ".\freddypharkas-cd.svm\freddypharkas-cd.scummvm"
del ".\elvira1.svm\elvira1.scummvm"
del ".\hoyle2.svm\hoyle2.scummvm"
del ".\drascula.svm\drascula.scummvm"
del ".\elvira2.svm\Elvira 2 - The Jaws Of Cerberus.scummvm"
echo bargon > ".\bargon.svm\Bargon Attack.scummvm"
echo bbvs > ".\bbvs-win.svm\Beavis and Butt-head in Virtual Stupidity.scummvm"
echo bc > ".\bc.svm\The Black Cauldron.scummvm"
echo bladerunner > ".\bladerunner-win.svm\Blade Runner.scummvm"
echo blueforce > ".\Blue Force (CD DOS).svm\Blue Force.scummvm"
echo sword2 > ".\Broken Sword 2 The Smoking Mirror (CD Windows).svm\Broken Sword II - The Smoking Mirror.scummvm"
echo tucker > ".\Bud Tucker in Double Trouble (CD DOS).svm\Bud Tucker In Double Trouble.scummvm"
echo camelot > ".\camelot.svm\Conquests Of Camelot - The Search For The Grail.scummvm"
echo castlebrain > ".\Castle of Dr. Brain (CD DOS).svm\Castle of Dr. Brain.scummvm"
echo comi > ".\comi.svm\Curse of Monkey Island, The.scummvm"
echo cruise > ".\Cruise for a Corpse (VGA DOS).svm\Cruise for a Corpse.scummvm"
echo tentacle > ".\Day Of The Tentacle (CD Dos).svm\Maniac Mansion - Day of the Tentacle.scummvm"
echo dig > ".\dig.svm\Dig, The.scummvm"
echo dw > ".\Discworld 1 (CD DOS v2).svm\Discworld.scummvm"
echo draci > ".\draci.svm\Dragon History.scummvm"
echo drascula > ".\drascula.svm\Drascula - The Vampire Strikes Back.scummvm"
echo dreamweb > ".\Dreamweb (CD DOS).svm\Dreamweb.scummvm"
echo ecoquest > ".\EcoQuest 1 - The Search for Cetus (CD DOS).svm\EcoQuest - The Search for Cetus.scummvm"
echo ecoquest2 > ".\ecoquest2.svm\Lost Secret of the Rainforest.scummvm"
echo elvira1 > ".\elvira1.svm\Elvira - Mistress Of The Dark.scummvm"
echo elvira2 > ".\elvira2.svm\Elvira 2 - The Jaws Of Cerberus.scummvm"
echo eob > ".\Eye of the Beholder (CD DOS).svm\Eye Of The Beholder.scummvm"
echo eob2 > ".\Eye of the Beholder II - The Legend of Darkmoon (CD DOS).svm\Eye Of The Beholder 2 - The Legend Of Darkmoon.scummvm"
echo fairytales > ".\fairytales.svm\Mixed-up Fairy Tales.scummvm"
echo fascination > ".\fascination.svm\Fascination.scummvm"
echo feeble > ".\feeble-win.svm\The Feeble Files.scummvm"
echo queen > ".\Flight of the Amazon Queen (CD DOS).svm\Flight Of The Amazon Queen.scummvm"
echo freddypharkas > ".\freddypharkas-cd.svm\Freddy Pharkas - Frontier Pharmacist.scummvm"
echo ft > ".\Full Throttle (CD DOS).svm\Full Throttle.scummvm"
echo fw > ".\Future Wars (CD DOS).svm\Future Wars - Adventures In Time.scummvm"
echo gk1 > ".\Gabriel Knight Sins Of The Fathers (CD DOS).svm\Gabriel Knight - Sins Of The Fathers.scummvm"
echo gk2 > ".\gk2.svm\Beast Within - A Gabriel Knight Mystery, The.scummvm"
echo gob1 > ".\gob1cd-us.svm\Gobliins.scummvm"
echo gob3 > ".\gob3cd.svm\Goblins Quest 3 (CD DOS).scummvm"
echo gob2 > ".\Gobliins 2 (CD DOS).svm\Gobliins 2 - The Prince Buffoon.scummvm"
echo goldrush > ".\goldrush.svm\Gold Rush!.scummvm"
echo hoyle1 > ".\hoyle1.svm\Hoyle's Official Book Of Games - Volume 1.scummvm"
echo hoyle2 > ".\hoyle2.svm\Hoyle's Official Book Of Games - Volume 2.scummvm"
echo hoyle3 > ".\hoyle3.svm\Hoyle's Official Book Of Games - Volume 3.scummvm"
echo iceman > ".\iceman.svm\Codename - Iceman.scummvm"
echo ihnm > ".\ihnm.svm\I Have No Mouth, And I Must Scream.scummvm"
echo atlantis > ".\Indiana Jones and the Fate of Atlantis (CD DOS).svm\Indiana Jones and the Fate of Atlantis.scummvm"
echo indy3 > ".\Indiana Jones and the Last Crusade (FM Towns).svm\Indiana Jones and the Last Crusade.scummvm"
echo islandbrain > ".\Island of Dr. Brain (Floppy DOS).svm\Island of Dr. Brain, The.scummvm"
echo ite > ".\ite-cd.svm\Inherit the Earth - Quest for the Orb.scummvm"
echo kq5 > ".\King's Quest 5 - Absence Makes the Heart go Yonder (CD DOS).svm\King's Quest V - Absence Makes the Heart Go Yonder.scummvm"
echo kq6 > ".\King's Quest 6 - Heir Today, Gone Tomorrow (CD DOS, Windows).svm\King's Quest VI - Heir Today, Gone Tomorrow.scummvm"
echo kq7 > ".\King's Quest 7 - The Princeless Bride (CD DOS).svm\King's Quest 7 - The Princeless Bride.scummvm"
echo kq1sci > ".\kq1sci.svm\King's Quest I - Quest for the Crown.scummvm"
echo kq2 > ".\kq2.svm\King's Quest II - Romancing the Throne.scummvm"
echo kq3 > ".\kq3.svm\King's Quest 3 - To Heir Is Human.scummvm"
echo kq4sci > ".\kq4sci.svm\King's Quest IV - The Perils of Rosella.scummvm"
echo kyra3 > ".\kyra3.svm\The Legend of Kyrandia - Book III - Malcolm's Revenge.scummvm"
echo lol > ".\Lands of Lore - The Throne of Chaos (CD DOS, Multilanguage).svm\Lands Of Lore - The Throne Of Chaos.scummvm"
echo laurabow2 > ".\laurabow2-cd.svm\Laura Bow 2  The Dagger of AmonRa (CD DOS).scummvm"
echo lsl6 > ".\Leisure Suit Larry 6 - Shape Up or Slip Out (CD DOS).svm\Leisure Suit Larry 6 - Shape Up or Slip Out!.scummvm"
echo lsl7 > ".\Leisure Suit Larry 7 - Love for Sail (CD DOS).svm\Leisure Suit Larry 7 - Love For Sail!.scummvm"
echo lgop2 > ".\lgop2.svm\Leather Goddesses of Phobos! 2 - Gas Pump Girls Meet the Pulsating Inconvenience from Planet X.scummvm"
echo longbow > ".\longbow.svm\Conquests Of The Longbow - The Legend Of Robin Hood.scummvm"
echo loom > ".\loom-vga.svm\Loom.scummvm"
echo lit > ".\Lost in Time (CD DOS, Multilanguage).svm\Lost In Time.scummvm"
echo lsl1sci > ".\lsl1sci.svm\Leisure Suit Larry in the Land of the Lounge Lizards.scummvm"
echo lsl2 > ".\lsl2.svm\Leisure Suit Larry Goes Looking For Love.scummvm"
echo lsl3 > ".\lsl3.svm\Leisure Suit Larry III - Passionate Patti in Pursuit of the Pulsating Pectorals.scummvm"
echo lsl5 > ".\lsl5.svm\Leisure Suit Larry 5 - Passionate Patti Does Some Undercover Work.scummvm"
echo lure > ".\Lure of the Temptress (Floppy DOS).svm\Lure Of The Temptress.scummvm"
echo manhole > ".\manhole-cd.svm\Manhole, The  Enhanced (CD Windows).scummvm"
echo maniac > ".\Maniac Mansion (Amiga).svm\Maniac Mansion.scummvm"
echo mh1 > ".\mh1.svm\Manhunter - New York.scummvm"
echo mh2 > ".\mh2.svm\Manhunter 2 - San Francisco.scummvm"
echo monkey > ".\monkey.svm\The Secret of Monkey Island.scummvm"
echo monkey2 > ".\monkey2.svm\Monkey Island 2 - LeChuck's Revenge.scummvm"
echo neverhood > ".\neverhood.svm\Neverhood, The.scummvm"
echo nippon > ".\nippon.svm\Nippon Safes, Inc..scummvm"
echo pepper > ".\pepper.svm\Pepper's Adventures In Time.scummvm"
echo pn > ".\personalnightmare.svm\Personal Nightmare.scummvm"
echo phantasmagoria > ".\Phantasmagoria (CD, Windows).svm\Phantasmagoria.scummvm"
echo phantasmagoria2 > ".\phantasmagoria2.svm\Phantasmagoria - A Puzzle of Flesh.scummvm"
echo pq4 > ".\Police Quest 4 - Open Season (CD DOS).svm\Police Quest 4 - Open Season.scummvm"
echo pq1sci > ".\pq1sci.svm\Police Quest 1 - In Pursuit of the Death Angel VGA.scummvm"
echo pq2 > ".\pq2.svm\Police Quest 2 - The Vengeance.scummvm"
echo pq3 > ".\pq3.svm\Police Quest 3 - The Kindred.scummvm"
echo qfg1vga > ".\qfg1vga.svm\Hero's Quest - So You Want to Be a Hero.scummvm"
echo qfg2 > ".\qfg2.svm\Quest for Glory II - Trial by Fire.scummvm"
echo qfg3 > ".\qfg3.svm\Quest for Glory III - Wages of War.scummvm"
echo qfg4 > ".\qfg4.svm\Quest for Glory IV - Shadows of Darkness.scummvm"
echo rama > ".\RAMA (CD Windows).svm\Rama.scummvm"
echo ringworld2 > ".\Return to Ringworld (CD DOS).svm\Return to Ringworld.scummvm"
echo ringworld > ".\Ringworld - Revenge of the Patriarch (CD DOS).svm\Ringworld - Revenge of the Patriarch.scummvm"
echo samnmax > ".\Sam and Max Hit the Road (CD DOS).svm\Sam and Max Hit the Road.scummvm"
echo shivers > ".\Shivers (CD, Windows).svm\Shivers.scummvm"
echo simon1 > ".\Simon the Sorcerer 1 (CD Windows).svm\Simon The Sorcerer.scummvm"
echo simon2 > ".\Simon the Sorcerer 2 (CD Windows).svm\Simon The Sorcerer 2 - The Lion, The Wizard And The Wardrobe.scummvm"
echo sky > ".\sky.svm\Beneath a Steel Sky.scummvm"
echo sq4 > ".\Space Quest 4 - Roger Wilco and the Time Rippers (CD DOS).svm\Space Quest IV - Roger Wilco and the Time Rippers.scummvm"
echo sq6 > ".\Space Quest 6 - The Spinal Frontier (CD DOS).svm\Space Quest 6 - Roger Wilco in the Spinal Frontier.scummvm"
echo sq1sci > ".\sq1sci.svm\Space Quest I - Roger Wilco in the Sarien Encounter.scummvm"
echo sq2 > ".\sq2.svm\Space Quest 2 - Vohaul's Revenge.scummvm"
echo sq3 > ".\sq3.svm\Space Quest 3 - The Pirates Of Pestulon.scummvm"
echo sq5 > ".\sq5.svm\Space Quest 5 - The Next Mutation.scummvm"
echo sword1 > ".\sword1.svm\Broken Sword - The Shadow of the Templars.scummvm"
echo sword25 > ".\sword25.svm\Broken Sword 2.5 - The Return Of The Templars.scummvm"
echo t7g > ".\t7g.svm\The 7th Guest.scummvm"
echo teenagent > ".\teenagent.svm\Teen Agent.scummvm"
echo pegasus > ".\The Journeyman Project - Pegasus Prime (CD Mac).svm\Journeyman Project - Pegasus Prime, The.scummvm"
echo kyra1 > ".\The Legend of Kyrandia 1 (CD DOS).svm\The Legend of Kyrandia - Book One.scummvm"
echo kyra2 > ".\The Legend of Kyrandia 2 The Hand of Fate (CD DOS).svm\The Legend of Kyrandia - Hand of Fate.scummvm"
echo toon > ".\toon.svm\Toonstruck.scummvm"
echo torin > ".\Torins Passage (CD Windows).svm\Torin's Passage.scummvm"
echo touche > ".\Touche - The Adventures of the Fifth Musketeer (CD DOS).svm\Touche - The Adventures of the Fifth Musketeer.scummvm"
echo troll > ".\troll.svm\Troll's Tale.scummvm"
echo urban > ".\urban-us.svm\Urban Runner.scummvm"
echo versailles > ".\versailles.svm\Versailles 1685.scummvm"
echo voyeur > ".\Voyeur (CD DOS).svm\Voyeur.scummvm"
echo waxworks > ".\Waxworks (Amiga).svm\Waxworks.scummvm"
echo ween > ".\Ween The Prophecy (Amiga).svm\Ween - The Prophecy.scummvm"
echo woodruff > ".\woodruff-gb.svm\Bizarre Adventures Of Woodruff And The Schnibble, The.scummvm"
echo zak > ".\Zak McKracken and the Alien Mindbenders (Amiga).svm\Zak Mckracken And The Alien Mindbenders.scummvm"
echo zgi > ".\zgi-win.svm\Zork - Grand Inquisitor.scummvm"
pause